apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  serviceAccountName: flux-platform-reconciler
  targetNamespace: external-dns
  sourceRef:
    kind: GitRepository
    name: black-quartz-platform
  path: kubernetes/components/external-dns
  interval: 10m
  prune: true
  dependsOn:
    - name: platform-network-policies
    - name: platform-identity
