apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../lib/role_definitions/gateway-route-contributor.yml
  - ../../../lib/role_definitions/github-runner-set-contributor.yml
  - ../../../lib/role_definitions/vault-kubernetes-secrets-engine.yml
  - ../../../lib/role_definitions/vector-agent.yml
  - ../../../lib/role_bindings/flux-github-runner-set-contributor.yml
  - ../../../lib/role_bindings/vault-kubernetes-auth-backend.yml
  - ../../../lib/role_bindings/vault-kubernetes-secrets-engine.yml
  - ../../../lib/role_bindings/vector-agent.yml
