apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: black-quartz-platform
  namespace: flux-system
spec:
  type: github
  address: https://github.com/black-quartz/black-quartz-platform
  secretRef:
    name: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: black-quartz-platform-commit-status
  namespace: flux-system
spec:
  providerRef:
    name: black-quartz-platform
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: platform-namespaces
    - kind: Kustomization
      name: platform-identity
    - kind: Kustomization
      name: cert-manager
    - kind: Kustomization
      name: envoy-gateway
    - kind: Kustomization
      name: external-dns