apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: flux-fleet-management
  namespace: flux-system
spec:
  type: github
  address: https://github.com/black-quartz/flux-fleet-management
  secretRef:
    name: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: flux-fleet-management-commit-status
  namespace: flux-system
spec:
  providerRef:
    name: flux-fleet-management
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: flux-system
