apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
    reconcile.fluxcd.io/watch: Enabled
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
data:
  ENVIRONMENT: production
  CLUSTER_NAME: prod-us-1
  CLUSTER_DOMAIN: prod-us-1.ilysium.io
  CLUSTER_TYPE: kubernetes
  CLUSTER_ROLE: hub
