apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-kubernetes-secrets-engine
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "delete", "get"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings", "clusterrolebindings"]
    verbs: ["create", "delete", "get"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "clusterroles"]
    verbs: ["bind", "escalate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-kubernetes-secrets-engine-binding
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-kubernetes-secrets-engine
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-kubernetes-auth-backend-binding
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
