apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/flux-instance.yml
  - flux-system/flux-operator.yml
  - flux-system/runtime-info.yml
  - policy.yml
  - tenants.yml
configMapGenerator:
  - name: infra-tenants
    namespace: flux-system
    files:
      - ../../tenants/infra.yml
  - name: app-tenants
    namespace: flux-system
    files:
      - ../../tenants/apps.yml
generatorOptions:
  disableNameSuffixHash: true
