apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux Identity
  - ../../identity/service-accounts/flux-platform-reconciler.yml
  # Flux Kustomizations
  - ../../kustomizations/black-quartz-platform.yml
  - ../../kustomizations/cert-manager.yml
  - ../../kustomizations/envoy-gateway.yml
  - ../../kustomizations/external-dns.yml
  - ../../kustomizations/vault-deployment.yml
  # Repositories
  - ../../repositories/black-quartz-platform.yml
  - ../../repositories/vault-deployment.yml
  # Notification Resources
  - ../../notifications/github/black-quartz-platform.yml
  - ../../notifications/github/flux-fleet-management.yml
  - ../../notifications/github/vault-deployment.yml
  - ../../notifications/slack/deployments-channel.yml
