apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Sources
  - ../../sources/black-quartz-platform.yml
  
  # Notification Resources
  - ../../notifications/github.yml
  - ../../notifications/slack.yml
  - ../../notifications/alerts.yml
  

