apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Flux Identity
  - ../../identity/flux-deploy.yml

  # Sources
  - ../../repositories/cert-manager-deployment.yml
  - ../../repositories/black-quartz-platform.yml

  # Notification Resources
  - ../../notifications/github.yml
  - ../../notifications/slack.yml
  - ../../notifications/alerts.yml
