apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra-resourceset.yml
configMapGenerator:
  - name: infra-tenants
    files:
      - inputs.yml
generatorOptions:
  disableNameSuffixHash: true
