apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: helmreleases.helm.toolkit.fluxcd.io
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: longhorn-system
        labels:
          pod-security.kubernetes.io/enforce: "privileged"

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      metadata:
        name: longhorn
        namespace: longhorn-system
      spec:
        interval: 10m
        url: https://charts.longhorn.io

    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: longhorn
        namespace: longhorn-system
      spec:
        serviceAccountName: flux-operator
        interval: 30m
        chart:
          spec:
            chart: longhorn
            version: "1.12.x"
            sourceRef:
              kind: HelmRepository
              name: longhorn
            interval: 12h
        releaseName: longhorn
        install:
          strategy:
            name: RetryOnFailure
            retryInterval: 3m
        upgrade:
          force: true
          strategy:
            name: RetryOnFailure
            retryInterval: 3m
        values:
          defaultSettings:
            defaultReplicateCount: 1
            defaultDataLocality: best-effort
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 1
            defaultFsType: ext4
          service:
            ui:
              type: ClusterIP
          longhornUI:
            log:
              format: json
          longhornManager:
            log:
              format: json
          longhornDriver:
            log:
              format: json
