apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/flux-instance.yml
  - flux-system/flux-operator.yml
  - flux-system/runtime-info.yml
  - components.yml
  - policy.yml
  - rbac.yml
  - tenants.yml
