apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: global-tenants
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: platform-tenants
      namespace: flux-system
      ready: true

  inputs:
    - name: arc-runners
      namespace: arc-runners
      podSecurityEnforce: baseline
      repository:
        url: https://github.com/black-quartz/actions-runner-scale-set-deployment
        ref:
          branch: main
        path: ./kubernetes/${ENVIRONMENT}

    - name: vector
      namespace: vector
      podSecurityEnforce: privileged
      repository:
        url: https://github.com/black-quartz/vector-deployment
        ref:
          branch: main
        path: ./kubernetes/${ENVIRONMENT}

  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.namespace >>
        labels:
          toolkit.fluxcd.io/role: "tenant"
          pod-security.kubernetes.io/enforce: << inputs.podSecurityEnforce >>
          pod-security.kubernetes.io/enforce-version: latest

    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: flux-runtime-info
        namespace: << inputs.namespace >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/flux-runtime-info"
        labels:
          reconcile.fluxcd.io/watch: Enabled

    - apiVersion: v1
      kind: Secret
      metadata:
        name: github-auth
        namespace: << inputs.namespace >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/github-auth"
      type: Opaque

    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: flux
        namespace: << inputs.namespace >>

    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: flux
        namespace: << inputs.namespace >>
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: admin
      subjects:
        - kind: ServiceAccount
          name: flux
          namespace: << inputs.namespace >>

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: << inputs.name >>
        namespace: << inputs.namespace >>
      spec:
        interval: 5m
        provider: github
        url: << inputs.repository.url >>
        ref:
          branch: << inputs.repository.ref.branch >>
        secretRef:
          name: github-auth

    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: << inputs.name >>
        namespace: << inputs.namespace >>
      spec:
        targetNamespace: << inputs.namespace >>
        serviceAccountName: flux
        interval: 30m
        retryInterval: 5m
        wait: true
        timeout: 5m
        sourceRef:
          kind: GitRepository
          name: << inputs.name >>
        path: << inputs.repository.path >>
        prune: true
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: flux-runtime-info

    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Provider
      metadata:
        name: github-provider
        namespace: << inputs.namespace >>
      spec:
        type: github
        address: << inputs.repository.url >>
        secretRef:
          name: github-auth

    - apiVersion: notification.toolkit.fluxcd.io/v1beta3
      kind: Alert
      metadata:
        name: github-commit-status
        namespace: << inputs.namespace >>
      spec:
        providerRef:
          name: github-provider
        eventSeverity: info
        eventSources:
          - kind: Kustomization
            name: << inputs.name >>
