apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infra-tenants
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileEvery: "5m"
spec:
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: flux-source-policy
      namespace: flux-system
      ready: true
      readyExpr: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')

  inputs:
    - tenant: cert-manager
      namespace: cert-manager

    - tenant: envoy-gateway
      namespace: envoy-gateway-system

  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.namespace >>

    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: flux-runtime-info
        namespace: << inputs.namespace >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/flux-runtime-info"
        labels:
          reconcile.fluxcd.io/watch: Enabled

    - apiVersion: v1
      kind: Secret
      metadata:
        name: github-auth
        namespace: << inputs.namespace >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/github-auth"
      type: Opaque

    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: flux
        namespace: << inputs.namespace >>

    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: flux-infra-<< inputs.tenant >>
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
        - kind: ServiceAccount
          name: flux
          namespace: << inputs.namespace >>

    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      metadata:
        name: flux-infra-management
        namespace: << inputs.namespace >>
      spec:
        interval: 5m
        serviceAccountName: flux
        url: "https://github.com/black-quartz/flux-infra-management.git"
        ref:
          branch: main

    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: infra-controllers
        namespace: << inputs.namespace >>
      spec:
        targetNamespace: << inputs.namespace >>
        serviceAccountName: flux
        interval: 30m
        retryInterval: 5m
        wait: true
        timeout: 5m
        sourceRef:
          kind: GitRepository
          name: flux-infra-management
        path: "./components/<< inputs.tenant >>/controllers/${ENVIRONMENT}"
        prune: true
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: flux-runtime-info

    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: infra-configs
        namespace: << inputs.namespace >>
      spec:
        dependsOn:
          - name: infra-controllers
        targetNamespace: << inputs.namespace >>
        serviceAccountName: flux
        interval: 30m
        retryInterval: 5m
        wait: true
        timeout: 5m
        sourceRef:
          kind: GitRepository
          name: flux-infra-management
        path: "./components/<< inputs.tenant >>/configs/${ENVIRONMENT}"
        prune: true
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: flux-runtime-info
