apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-cert-manager-reconciler
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-cert-manager-reconciler-binding
  namespace: cert-manager
subjects:
  - kind: ServiceAccount
    name: flux-cert-manager-reconciler
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
