apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-platform-reconciler
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-platform-reconciler-binding
subjects:
  - kind: ServiceAccount
    name: flux-platform-reconciler
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
